CREATE TABLE COMMON_USER (
	ID INTEGER NOT NULL DEFAULT NEXTVAL('COMMON_USER_SEQ'::REGCLASS),
	NAME  		CHARACTER VARYING(200) NULL,
	LOGIN 		CHARACTER VARYING(20) NOT NULL,
	PASSWORD 	CHARACTER VARYING(8) NOT NULL,
	LOCALE		CHARACTER (2) NOT NULL,
	ORIGIN		CHARACTER (1) NOT NULL DEFAULT 0,
	CONSTRAINT COMMON_USER_PK PRIMARY KEY (ID),
	CONSTRAINT LOGIN_UNIQUE UNIQUE (LOGIN)
);